[package]
name = "chinese-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.33.0"
eframe = "0.33.0"
image = "0.25.8"
anyhow = "1.0.100"
resvg = "0.45.1"
usvg = "0.45.1"
tiny-skia = "0.11.4"
egui_extras = { version = "0.33.0", features = ["svg"] }