[package]
name = "chinese-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27"
eframe = "0.27"
image = "0.25"
anyhow = "1.0"
resvg = "0.39"
usvg = "0.39"
tiny-skia = "0.11"
egui_extras = { version = "0.27", features = ["svg"] }